added getting all deputies and group by party
kenu21/jv-deputies pull request #13
Opened 2019-11-11 19:01 UTC by kenu21

2019-11-11 19:07 UTC, RomanMinevich approved these changes

2019-11-11 19:11 UTC, gkhrshch approved these changes

2019-11-12 07:35 UTC, boroda4436 requested changes

2019-11-12 07:35 UTC, boroda4436 commented on src/main/java/com/statistic/deputies/controller/DeputyController.java
> +    @GetMapping("/getAllDeputiesGroupByParty")
@kenu21 немає сенсу дублювати deputy адже в тебе ця приставка вже є в контроллері
```suggestion
    @GetMapping("/getGroupedByParty")
```

Приставку all також можна прибрати, адже в майбутньому ти можеш додати деякі фільтри до цього запиту

2019-11-12 07:35 UTC, boroda4436 commented on src/main/java/com/statistic/deputies/controller/DeputyController.java
> +                                                    @RequestParam String endWork) {
@kenu21 розглядав кейс коли endWork може бути меншим за startWork?

2019-11-12 07:37 UTC, kenu21 commented on src/main/java/com/statistic/deputies/controller/DeputyController.java
> +    @GetMapping("/getAllDeputiesGroupByParty")
ОК.

2019-11-12 07:49 UTC, kenu21 commented on src/main/java/com/statistic/deputies/controller/DeputyController.java
> +                                                    @RequestParam String endWork) {
Тільки-но розглянув. Буде пустий ліст. Думаю, це логічно.

2019-11-12 07:57 UTC, boroda4436 approved these changes

2019-11-12 08:00 UTC, merged