Added notPoliticians() and deputiesWithAwards() controllers
kenu21/jv-deputies pull request #9
Opened 2019-11-08 14:58 UTC by RomanMinevich

2019-11-08 15:03 UTC, kenu21 approved these changes

2019-11-08 16:41 UTC, gkhrshch approved these changes

2019-11-11 09:28 UTC, boroda4436 requested changes

2019-11-11 09:28 UTC, boroda4436 commented on src/main/java/com/statistic/deputies/ParseData.java
>                  localDate = LocalDate.parse(deputies.get(i).get(7), dateTimeFormatter);
7 винеси як константу

2019-11-11 09:28 UTC, boroda4436 commented on src/main/java/com/statistic/deputies/ParseData.java
>              deputat.setParty(deputies.get(i).get(2));
2 винеси як константу

2019-11-11 09:28 UTC, boroda4436 commented on src/main/java/com/statistic/deputies/repository/DeputatRepository.java
> +    @Query("SELECT d FROM Deputat d WHERE d.rada = :rada")
@RomanMinevich А нам обов'язково писати аннотацію Query???Spring boot data JPA досить розумна і вона сама будує запити до БД на основі імені методу

2019-11-11 09:28 UTC, boroda4436 commented on src/main/java/com/statistic/deputies/repository/DeputatRepository.java
> +    List<Deputat> getDeputiesWithAwards();
@RomanMinevich Спробуй перейменувати метод і прибрати Query. Подивись чи відпрацює

2019-11-11 12:37 UTC, merged